---
title: "About"
description: |
  A personal website for Eli Pousson.
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Hello! My name is Eli Pousson. I am a planner and program coordinator with the [Neighborhood Design Center](https://ndc-md.org/), a Fellow with the Johns Hopkins University School of Public Health Bloomberg American Health Initiative, and local historian in Baltimore, Maryland.

I'm currently working a few R packages for mapping and analyzing data related to Baltimore City:

- [mapbaltimore](https://elipousson.github.io/mapbaltimore/)
- [bcpss](https://elipousson.github.io/bcpss/)
- [baltimoredata](https://elipousson.github.io/baltimoredata/)

I recently completed Master's of Public Health degree at Johns Hopkins University. My work during the program included completed [an analysis of 311 requests](https://elipousson.github.io/sewage-backups/index.html) for basement sewage backups in Baltimore and advocacy for the creation of Baltimore's Slow Streets program in early 2020.

Here are a few projects from my prior work at [Baltimore Heritage](https://baltimoreheritage.org):

- [Explore Baltimore Heritage](https://explore.baltimoreheritage.org/)
- [Baltimore’s Civil Rights Landmarks](https://baltimoreheritage.github.io/civil-rights-heritage/)